"""字幕烧录 - 将字幕嵌入视频（硬编码），支持样式自定义"""

import os
import subprocess
from pathlib import Path
from typing import Optional

from core.models import SubtitleSegment
from core.subtitle_style import SubtitleStyle, hex_to_ass


class SubtitleBurner:
    """将字幕烧录到视频中，支持自定义样式"""

    @classmethod
    def burn(
        cls,
        video_path: Path,
        segments: list[SubtitleSegment],
        output_path: Path,
        video_width: int = 1280,
        video_height: int = 720,
        style: Optional[SubtitleStyle] = None,
    ) -> Path:
        if not segments:
            raise ValueError("字幕片段为空，无法烧录")

        style = style or SubtitleStyle()

        # 计算字号 (相对视频高度)
        font_size = max(10, min(48, int(video_height * style.font_size_ratio)))

        # 字幕边距（固定底部居中）
        margin_v = max(20, video_height // 20)
        margin_l = video_width // 6
        margin_r = video_width // 6

        # 使用纯文件名（无路径）写入 ASS，避免 Windows 冒号在 ffmpeg filter 中解析错误
        ass_name = f"_tmp_sub_{video_path.stem}_.ass"
        ass_path = Path(ass_name)
        cls._write_ass(ass_path, segments, font_size, style, margin_l, margin_r, margin_v)

        print(f"  🔥 正在烧录字幕到视频...")
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_path),
            "-vf", f"ass={ass_name}",
            "-c:a", "copy",
            str(output_path),
        ]
        try:
            subprocess.run(cmd, capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"字幕烧录失败: {e.stderr.strip() or str(e)}")
        finally:
            if ass_path.exists():
                ass_path.unlink()

        if not output_path.exists():
            raise RuntimeError("字幕烧录失败: 输出文件未生成")

        return output_path

    @classmethod
    def _write_ass(
        cls,
        path: Path,
        segments: list[SubtitleSegment],
        font_size: int,
        style: SubtitleStyle,
        margin_l: int,
        margin_r: int,
        margin_v: int,
    ):
        """生成 ASS 字幕文件 (底部居中)"""
        primary = hex_to_ass(style.primary_color)
        outline = hex_to_ass(style.outline_color)
        bold = 1 if style.bold else 0

        lines = [
            "[Script Info]",
            "; ASS subtitle file generated by video-subtitle-generator",
            "Title: Video Subtitles",
            "ScriptType: v4.00+",
            "WrapStyle: 0",
            "ScaledBorderAndShadow: yes",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            f"Style: Default,{style.font_name},{font_size},{primary},&H000000FF,{outline},&H00000000,{bold},0,0,0,100,100,0,0,1,{style.outline_width},1,2,{margin_l},{margin_r},{margin_v},1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ]

        for seg in segments:
            start = cls._time_to_ass(seg.start_time)
            end = cls._time_to_ass(seg.end_time)
            text = seg.text.replace("{", "\\{").replace("}", "\\}")
            if seg.translated_text:
                trans = seg.translated_text.replace("{", "\\{").replace("}", "\\}")
                text = f"{trans}\\N{text}"
            lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")

        path.write_text("\n".join(lines), encoding="utf-8")

    @staticmethod
    def _time_to_ass(seconds: float) -> str:
        """秒 → H:MM:SS.cc (ASS 时间格式)"""
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int((seconds - int(seconds)) * 100)
        return f"{h}:{m:02d}:{s:02d}.{cs:02d}"
